### ISSUE TITLE
Signature Error while installing app on Emulator

### ISSUE THREAD

**Issue by mseo12** [SamsungDForum/JuvoPlayer#7] opened 2020-04-22 04:30 UTC
Hello~

We got "Signature error" below while installing app on the emulator.
I was downloading any other sample applications on the same emulator so guessing there would be  no certificate issue on my current setup.
To make test easy, unloaded Junoplayer.OpenGL/XamarinPlayer/ReactNative for now.

2020-04-21 오후 10:14:19 : <<< Start debugging "org.tizen.example.SimplePlayer.Tizen.TV" (secure protocol) >>>
2020-04-21 오후 10:14:19 : Try to terminate running application: org.tizen.example.SimplePlayer.Tizen.TV
2020-04-21 오후 10:14:19 : No application to be terminated: 255
	install: skip option is requested. 3
	WARNING: Your data are to be sent over an unencrypted connection and could be read by others.
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk	  0%	      0KB	    0KB/s
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk	 28%	   2944KB	    0KB/s
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk	100%	  10203KB	    0KB/s
	1 file(s) pushed. 0 file(s) skipped.
	C:\Project\JuvoPlayer\SimplePlayer.Tizen.TV\bin\Debug\tizen50\org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk   7675KB/s (10448578 bytes in 1.329s)
	install org.tizen.example.SimplePlayer.Tizen.TV
	package_path /home/owner/share/tmp/sdk_tools/org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] install start
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[12]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[15]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[18]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[21]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[25]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[28]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] install failed[118, -14], reason: **Signature error : 
	spend time for wascmd is [2431]ms**
2020-04-21 오후 10:14:26 : Removing port forward...
2020-04-21 오후 10:14:26 : Forwarding port...
2020-04-21 오후 10:14:26 : Launching org.tizen.example.SimplePlayer.Tizen.TV
2020-04-21 오후 10:14:27 : ... launch failed
2020-04-21 오후 10:19:53 : <<< Start debugging "org.tizen.example.SimplePlayer.Tizen.TV" (secure protocol) >>>
2020-04-21 오후 10:19:53 : Try to terminate running application: org.tizen.example.SimplePlayer.Tizen.TV
2020-04-21 오후 10:19:53 : No application to be terminated: 255
	install: skip option is requested. 3
	WARNING: Your data are to be sent over an unencrypted connection and could be read by others.
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk	  0%	      0KB	    0KB/s
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk	 58%	   6016KB	    0KB/s
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk	 98%	  10048KB	 3278KB/s
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk	100%	  10203KB	 3278KB/s
	1 file(s) pushed. 0 file(s) skipped.
	C:\Project\JuvoPlayer\SimplePlayer.Tizen.TV\bin\Debug\tizen50\org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk   5180KB/s (10448578 bytes in 1.969s)
	install org.tizen.example.SimplePlayer.Tizen.TV
	package_path /home/owner/share/tmp/sdk_tools/org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] install start
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[12]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[15]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[18]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[21]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[25]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[28]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] install failed[118, -14], reason: Signature error : 
	spend time for wascmd is [2247]ms
2020-04-21 오후 10:20:01 : Removing port forward...
2020-04-21 오후 10:20:02 : Forwarding port...
2020-04-21 오후 10:20:02 : Launching org.tizen.example.SimplePlayer.Tizen.TV
2020-04-21 오후 10:20:03 : ... launch failed
2020-04-21 오후 10:20:03 : 'org.tizen.example.SimplePlayer.Tizen.TV' is dependent on 'org.tizen.example.SimplePlayer.Tizen.TV-1.5.3.tpk'.

Thank you,

**Comment by mseo12** [comment] 2020-04-22 05:23
I was able to install XamarinPlayer.Tizen.TV, so guessing SimplePlayer doesn't work?

**Comment by pbsamsung** [comment] 2020-04-22 06:21
Hello, 
All the JuvoPlayer GUI's should work the same at the installation step. However the "Signature error" reported to SimplePlayer will be investigated. 
Thank You very much for the notification

**Comment by msavvicki** [comment] 2020-04-22 08:12
Hi,

"Signature error" usually is indicative of certificate not containing DUID (emulator/target) or certificate not being installed via Device Manager->right click on device->Permit to install.
Running through raised issue using VS2019 with Tizen Studio 3.7, I was unable to reproduce it, however, I had to assure:

- Certificates are generated and installed for each new emulator instance as they will have different DUIDs.
- If certificates are created while running VS, VS restart is required in order to use updated certificates.

Hope this helps.

**Comment by casic** [comment] 2020-11-27 14:03
I have installed  last Tizen packages ,  ands have the same   error.  
Generated  new certificates ,  DUID on emulator  , on Smart TV   again and  again , from scratch.   
No success.
11/27/2020 3:38:48 PM : <<< Start without debugging "org.tizen.example.SimplePlayer.Tizen.TV" (secure protocol) >>>
11/27/2020 3:38:48 PM : Try to terminate running application: org.tizen.example.SimplePlayer.Tizen.TV
11/27/2020 3:38:48 PM : No application to be terminated: 255
	WARNING: Your data are to be sent over an unencrypted connection and could be read by others.
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.5.tpk	  0%	      0MB	    0KB/s
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.5.tpk	 54%	      5MB	    0KB/s
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.5.tpk	 95%	      9MB	 3747KB/s
	pushed org.tizen.example.SimplePlayer.Tizen.TV-1.5.5.tpk	100%	     10MB	 3747KB/s
	1 file(s) pushed. 0 file(s) skipped.
	C:\Users\kostadin\Source\Repos\JuvoPlayer3\SimplePlayer.Tizen.TV\bin\Debug\tizen50\org.tizen.example.SimplePlayer.Tizen.TV-1.5.5.tpk   5457KB/s (10506597 bytes in 1.879s)
	install org.tizen.example.SimplePlayer.Tizen.TV
	package_path /home/owner/share/tmp/sdk_tools/org.tizen.example.SimplePlayer.Tizen.TV-1.5.5.tpk
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] install start
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[12]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[15]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[18]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[21]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[25]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] installing[28]
	app_id[org.tizen.example.SimplePlayer.Tizen.TV] install failed[118, -14], reason: Signature error : 
	spend time for wascmd is [1490]ms
11/27/2020 3:38:52 PM : Try to launch application: org.tizen.example.SimplePlayer.Tizen.TV
11/27/2020 3:38:52 PM : Application launched.
11/27/2020 3:40:50 PM : <<< Start without debugging "JuvoPlayerXamarin.Tizen.TV" (secure protocol) >>>
11/27/2020 3:40:50 PM : Try to terminate running application: JuvoPlayerXamarin.Tizen.TV
11/27/2020 3:40:50 PM : No application to be terminated: 255
	WARNING: Your data are to be sent over an unencrypted connection and could be read by others.
	pushed JuvoPlayerXamarin.Tizen.TV-1.5.5.tpk	  0%	      0KB	    0KB/s
	pushed JuvoPlayerXamarin.Tizen.TV-1.5.5.tpk	 66%	   5632KB	 7886KB/s
	pushed JuvoPlayerXamarin.Tizen.TV-1.5.5.tpk	100%	   8472KB	 7886KB/s
	1 file(s) pushed. 0 file(s) skipped.
	C:\Users\kostadin\Source\Repos\JuvoPlayer3\XamarinPlayer\XamarinPlayer.Tizen.TV\bin\Debug\tizen50\JuvoPlayerXamarin.Tizen.TV-1.5.5.tpk   3850KB/s (8675992 bytes in 2.200s)
	install JuvoPlayerXamarin.Tizen.TV
	package_path /home/owner/share/tmp/sdk_tools/JuvoPlayerXamarin.Tizen.TV-1.5.5.tpk
	app_id[JuvoPlayerXamarin.Tizen.TV] install start
	app_id[JuvoPlayerXamarin.Tizen.TV] installing[12]
	app_id[JuvoPlayerXamarin.Tizen.TV] installing[15]
	app_id[JuvoPlayerXamarin.Tizen.TV] installing[18]
	app_id[JuvoPlayerXamarin.Tizen.TV] installing[21]
	app_id[JuvoPlayerXamarin.Tizen.TV] installing[25]
	app_id[JuvoPlayerXamarin.Tizen.TV] installing[28]
	app_id[JuvoPlayerXamarin.Tizen.TV] install failed[118, -14], reason: Signature error : 
	spend time for wascmd is [908]ms

**Comment by ppaneksamsung** [comment] 2020-12-03 21:12
@casic,

Sorry for late reply. Could you make sure that you generate certificates as described in this tutorial: https://developer.samsung.com/smarttv/develop/getting-started/setting-up-sdk/creating-certificates.html ? In case of our applications, it's important to set the privilege level to 'Partner' instead of 'Public' (see step 8.2).

**Comment by casic** [comment] 2020-12-04 15:02
Thanks.  
 "Partner"  is the  KEY.   
Now work on Emulator.
My TV is  tizen 4.0.    Will  be  work on it ?
I try to start , but  nothing happened.
Best regards.

**Comment by ppaneksamsung** [comment] 2020-12-04 15:41
@casic,

JuvoPlayer uses the Tizen.TV.Multimedia.ESPlayer API, which is available since 2019 TVs (Tizen 5.0). We don't test our applications on Tizen 4.0 as noted here (see step 3.):
https://github.com/SamsungDForum/JuvoPlayer/blob/master/docs/dependencies.md

**Comment by a4tech** [comment] 2022-08-08 21:20
Guys, anyone get luck with that ?

I struggeling to install any of upper apps. Even cert is generated correctly: I tested public and parener type - both have same issue. Certificate is installed to emulator correctly. Any idea what to do ?

**Closed** 2023-09-13 13:23 UTC
