### ISSUE TITLE
Application refers a forbidden assembly directly

### ISSUE THREAD

**Issue by tiagommferreira** [SamsungDForum/JuvoPlayer#6] opened 2019-10-26 10:29 UTC
When launching the UI Applications on a 2019 Samsung SmartTV, I'm getting the following errors:

> [FAIL] SimplePlayer.Tizen.TV.dll refers a forbidden assembly directly - Xamarin.Forms.Core :( 

> [FAIL] JuvoPlayer.Xamarin.Tizen.TV.dll refers a forbidden assembly directly - Xamarin.Forms.Platform.Tizen :(

> [FAIL] JuvoPlayerOpenGLNative.Tizen.TV.dll refers a forbidden assembly directly - JuvoPlayer :(

Launching the ReactNative one just shows a black screen.

Additional information:
Model Number: QE49Q67RATXXC
Sofware Version: T-MSMDEUC-1315.4, B6912200/050204, BT-S

**Comment by pbsamsung** [comment] 2019-10-29 09:46
Hello,
For the moment there are only two options to launch the JuvoPlayer based applications successfully:
1) on the TV Emulator provided by the Tizen Tools package. It should just work with no more actions.
2) on a TV set if the particular unit DUID has been notified to Samsung. In this case You need to work for Samsung Partner Company. First contact local Content Manager and ask to be a Partner developer (You can use Samsung Seller Office site for that). Then the Partner developer can get information how to switch off the security verification mechanism (forbidden library message). 
Regards,
Pawel

**Comment by TobiStr** [comment] 2019-12-07 21:23
Hello,

I am trying to develop a xamarin app for tizen TV and get the same message by just using the template for tizen tv 5.0 xamarin apps:

> [FAIL] APPNAME.Tizen.TV.dll refers a forbidden assembly directly - Xamarin.Forms.Platform.Tizen :(

I've seen that the namespaces have changed, but updating the nuget packages and adapting to them didn't solve this error.

Furthermore my emulator doesn't work either, so i have no chance to see any results. Visual Studio always gives me the error:

> Error while trying to enter break state. Debuggiing will now stop. Failed to find thread xxxx for break event.

**Comment by polboo** [comment] 2019-12-09 06:42
> Hello,
> 
> I am trying to develop a xamarin app for tizen TV and get the same message by just using the template for tizen tv 5.0 xamarin apps:
> 
> > [FAIL] APPNAME.Tizen.TV.dll refers a forbidden assembly directly - Xamarin.Forms.Platform.Tizen :( 
[pbsamsung] It looks like the 'security policy checker' block's You app. Please, report it on [TV Apps seller office](https://seller.samsungapps.com/tv/portal/main) site to make sure. If Samsung provides You with the signature files for your TV unit this issue will gone.

**Comment by pbsamsung** [comment] 2019-12-09 07:01
> Hello,
> 
> I am trying to develop a xamarin app for tizen TV and get the same message by just using the template for tizen tv 5.0 xamarin apps:
> 
> > [FAIL] APPNAME.Tizen.TV.dll refers a forbidden assembly directly - Xamarin.Forms.Platform.Tizen :(
> 
> I've seen that the namespaces have changed, but updating the nuget packages and adapting to them didn't solve this error.
> 
> Furthermore my emulator doesn't work either, so i have no chance to see any results. Visual Studio always gives me the error:
> 
> > Error while trying to enter break state. Debuggiing will now stop. Failed to find thread xxxx for break event.

[pbsamsung] 
1) Make sure the version of the emulator is 'Tizen Studio for 5.0'. It was tested on the SDK version: 3.2, Package version 2.8.0.23, Build date 2019-05-15 06:24:01 IST.
2) I have noticed that on some PC's the default TV  emulator's VM needs to be deleted and crated again with the Tizen Studio Emulator tool. Please, try it too.
3) The debug mode launching may not work as intended. Please, launch it in release mode (ctrl+F5) ans see if it works for You.

**Comment by pbsamsung** [comment] 2019-12-09 07:32
Hi,
For the Visual Studio 2019 You need to make sure that the installed Tizen.NET.Sdk nuget version is not lower than 1.0.8. In case JuvoPlayer we are still using VS 2017 or VS Code and it is based on Tizen.NET.Sdk 1.0.1 version.

**Comment by TobiStr** [comment] 2019-12-09 20:07
Thank you very much!
Both problems were solved!

These were the steps i did:
1. Updated the first line in both .csproj-Files (APPNAME and APPNAME.Tizen.TV) from 

> Project Sdk="Tizen.NET.Sdk/1.0.3">

to

> Project Sdk="Tizen.NET.Sdk/1.0.8">
2. Updated the nuget packages to the latest version.
3. Changed the Init call in the Main-Method from:
> global::Xamarin.Forms.Platform.Tizen.Forms.Init(app);

to
> Xamarin.Forms.Forms.Init(app);
4. Recreated the TV Emulator like in your 2. point.

Btw Debug Mode works fine for me.
I am using Visual Studio 2019 on Windows 10.

**Comment by pbsamsung** [comment] 2019-12-10 07:12
You're welcome. Good luck in Your next Tizen .NET apps development steps Tobias!

**Comment by pbsamsung** [comment] 2019-12-10 07:14
> When launching the UI Applications on a 2019 Samsung SmartTV, I'm getting the following errors:
> 
> > [FAIL] SimplePlayer.Tizen.TV.dll refers a forbidden assembly directly - Xamarin.Forms.Core :(
> 
> > [FAIL] JuvoPlayer.Xamarin.Tizen.TV.dll refers a forbidden assembly directly - Xamarin.Forms.Platform.Tizen :(
> 
> > [FAIL] JuvoPlayerOpenGLNative.Tizen.TV.dll refers a forbidden assembly directly - JuvoPlayer :(
> 
> Launching the ReactNative one just shows a black screen.
> 
> Additional information:
> Model Number: QE49Q67RATXXC
> Sofware Version: T-MSMDEUC-1315.4, B6912200/050204, BT-S

Hello Tiago,
Please, verify if the solution that worked out for Tobias does solve the issue on Your side. If so Than I'd like to close this thread.
Regards,
Pawel

**Comment by gamukeat** [comment] 2020-05-07 19:52
Do you have any suggestion for SkiaSharp?

I'm using version mentioned in JuvoPlayer (1.60 with and without token) 
App signed with my partner privilege certificate, and unsuccess.

App wont to start.

**Comment by ppaneksamsung** [comment] 2020-05-08 07:35
> Do you have any suggestion for SkiaSharp?

Would you like to use SkiaSharp in Xamarin.Forms application? Tizen 5.5 supports 1.60.3 version, however there are some things to mention:
- You have to remove all SkiaSharp binaries from TPK. This is done by adding following entry to *.csproj file:
`<TizenTpkExcludePattern>runtimes\*\native\*.*</TizenTpkExcludePattern>`
see for reference: https://github.com/SamsungDForum/JuvoPlayer/blob/master/XamarinPlayer/XamarinPlayer.Tizen.TV/XamarinPlayer.Tizen.TV.csproj
- There was an ABI break in Xamarin.Forms (see https://github.com/xamarin/Xamarin.Forms/issues/9129) in version >= 4.2.0.709249, so if you want to use Xamarin.Forms in version >= 4.2.0.709249, then you should use our hijacked SkiaSharp.Views.Forms.dll and SkiaSharp.Views.Tizen.dll (available in https://github.com/SamsungDForum/JuvoPlayer/tree/master/XamarinPlayer/XamarinPlayer.Tizen.TV/packages). If you want to use Xamarin.Forms version < 4.2.0.709249, then you should use official SkiaSharp.Views.Forms.dll and SkiaSharp.Views.Tizen.dll - just add package reference SkiaSharp.Views.Forms in version 1.60.3.

If above tips don't help, please prepare a minimal sample application which shows the problem and share it with us. We will debug it on our side.

**Comment by gamukeat** [comment] 2020-05-08 21:44
Thank you for you answer, 
And is it supported by previous versions of tizen (4.0-5.0)?

**Comment by ppaneksamsung** [comment] 2020-05-13 08:04
Sorry fot late response,

SkiaSharp is not supported on Tizen 4.0. Only Tizen 5.0 and 5.5 supports it.

**Comment by FernetMenta** [comment] 2020-05-14 05:16
> Then the Partner developer can get information how to switch off the security verification mechanism

@pbsamsung could yo please elaborate on this process? I am partner developer and get this forbidden message.

**Comment by pbsamsung** [comment] 2020-05-14 06:21
Hello FernetMenta, 
What is the actual error message that You've got? If the recovery steps above didn't help You it may be a different problem. Please, let me know.

However, if You need to switch off the .dll files signing verification (only for development purpose) it is possible. First, You need to contact the Samsung Content Manager that is in charge of Your Partner agreement (contract). Usually it is a person working in local Samsung Office in Your Country of residence. It should be possible to find him out over the Samsung Seller Office site (https://seller.samsungapps.com/tv/assistance/csportal/list). If You provide me Your Seller Office user name I can help with this.

**Comment by FernetMenta** [comment] 2020-05-14 13:01
> What is the actual error message that You've got?

SkiaSharp.Views.Tizen.dll refers to a forbidden ... directly: libglesv2.so

![image](https://user-images.githubusercontent.com/576009/81937328-c9981400-95f3-11ea-84af-330cbc191468.png)

**Comment by pbsamsung** [comment] 2020-05-14 14:17
I seems that you will be needing the additional certificate for solving the problem. Please, let me know Your Seller Office user or/and company name. At least region (country) that Your App is going to be launched will be necessary. It is required to catch You on the Samsung Seller Office site.

**Comment by FernetMenta** [comment] 2020-05-14 15:20
> Please, let me know Your Seller Office user

user: rainer.hochecker@gmail.com
group rhocheck in Germany

**Comment by pbsamsung** [comment] 2020-05-15 06:10
Thank You. I'll let You know the result and the next steps as soon as possible. This process usually takes several days.

**Comment by Gabriela-C** [comment] 2020-05-16 00:56
Hello eveyone.
I'm a Tizen developer and I cannot run my application on the emulator TV. I got the next error:
[Fail] Tizen.TV.Security.dll refers a forbidden assembly directly -securestorage-client

![image](https://user-images.githubusercontent.com/56008191/82106229-81045780-96d4-11ea-8d00-9f483612092f.png)

I'm working with Visual studio 2017.
I'm developing a NUI application

Regards.

**Comment by ppaneksamsung** [comment] 2020-05-18 09:37
Hello,

> I'm a Tizen developer and I cannot run my application on the emulator TV. I got the next error:
[Fail] Tizen.TV.Security.dll refers a forbidden assembly directly -securestorage-client

I cannot reproduce your problem, but I have a few questions:
- Do you have the authority to use Tizen.TV.Service.UtteranceRecommender package? It seems to be the internal package.
- Could you share what is in your 'tpkroot/bin' directory? It is usually located in ProjectDir/bin/{Debug/Release}/{TargetFramework}/tpkroot/bin.
- Did you add '\<ExcludeAssets\>Runtime\</ExcludeAssets\>' entry for Tizen.NET.TV and Tizen.TV.Service.UtteranceRecommender packages in your csproj file? For example:
```
    <PackageReference Include="Tizen.NET.TV" Version="<your_version>">
      <ExcludeAssets>Runtime</ExcludeAssets>
    </PackageReference>
```

**Comment by Gabriela-C** [comment] 2020-05-18 19:12
Thank you very much @ppaneksamsung I added the tag '<ExcludeAssets>' and it works, thank you for your help =)

**Comment by pbsamsung** [comment] 2020-05-20 11:57
Dear All, 

This is just a kind reminder that all the requests for switching-off the security checkup for development purposes requires Partnership relation with Samsung. See the  official 'How to become a partner'  guide on https://developer.samsung.com/smarttv/develop/distribute/seller-office/membership/partnership-request.html page. 
Without positive cross checking on https://seller.samsungapps.com/tv/ with a Content Manager in charge, we can't support You in this filed.

Best Regards,
JuvoPlayer Team

**Comment by aisgdevteam** [comment] 2020-06-01 08:53
Hi @pbsamsung 
I got error when I run on TV "SkiaSharp.Views.Tizenn.dll refers a forbideden assembly directly - liGlesv2.so" 
Do you have any suggestion for SkiaSharp?

**Comment by pbsamsung** [comment] 2020-06-01 09:41
Please, let me know your username at the https://seller.samsungapps.com/tv/  to help me in the cross-check with the CM in charge of Your region.

**Comment by aisgdevteam** [comment] 2020-06-02 01:09
> Hi @aisgdevteam
> Please, let me know your username at the https://seller.samsungapps.com/tv/ to help me in the cross-check with the CM in charge of Your region.
we've not yet upload apps. we're developing app.
my account bussiness: thachnn6@fpt.com.vn

Additional information:
Model Number: UA43T6000AKXXV
Sofware Version: T-KTS2UABC-1113.8

**Comment by pbsamsung** [comment] 2020-06-04 07:39
> > Hi @aisgdevteam
> > Please, let me know your username at the https://seller.samsungapps.com/tv/ to help me in the cross-check with the CM in charge of Your region.
> 
> we're developing app.
> my account bussiness: [aisg.devteam@gmail.com](mailto:aisg.devteam@gmail.com)
> group: SaiGonGroup Group
> Additional information:
> Model Number: UA43T6000AKXXV
> Sofware Version: T-KTS2UABC-1113.8

Hello,
I'm sorry but I was not able to match your contact details with the Samsung seller office site. Please, create a ticket (1:1 Q&A) out there containing an ask for contact in it's body'. I believe it is enough to write just : 
'I need to contact regarding the JuvoPlayer project. See https://github.com/SamsungDForum/JuvoPlayer/issues/6#issuecomment-636711490 for details.'
With that comment somebody from the Samsung apps support should react. 
If You have any other smart TV application uploaded to the seller office, please give the name of it. That also could help us.

**Comment by aisgdevteam** [comment] 2020-06-18 01:58
> > > Hi @aisgdevteam
> > > Please, let me know your username at the https://seller.samsungapps.com/tv/ to help me in the cross-check with the CM in charge of Your region.
> > 
> > 
> > we're developing app.
> > my account bussiness: [aisg.devteam@gmail.com](mailto:aisg.devteam@gmail.com)
> > group: SaiGonGroup Group
> > Additional information:
> > Model Number: UA43T6000AKXXV
> > Sofware Version: T-KTS2UABC-1113.8
> 
> Hello,
> I'm sorry but I was not able to match your contact details with the Samsung seller office site. Please, create a ticket (1:1 Q&A) out there containing an ask for contact in it's body'. I believe it is enough to write just :
> 'I need to contact regarding the JuvoPlayer project. See [#6 (comment)](https://github.com/SamsungDForum/JuvoPlayer/issues/6#issuecomment-636711490) for details.'
> With that comment somebody from the Samsung apps support should react.
> If You have any other smart TV application uploaded to the seller office, please give the name of it. That also could help us.

Hi @pbsamsung ,
My account is approved partnership. But I still got message "SkiaSharp.Views.Tizenn.dll refers a forbideden assembly directly - libglesv2.so" on TV when Ctrl + F5 test on TV
and I got message "reason: Author certificate not match" at Output in Visual.

**Comment by pbsamsung** [comment] 2020-06-19 08:18
Hello thachnn6@fpt.com.vn,
I was trying to find out the following users/groups at the Seller Office Site: SaiGonGroup,  thachnn6@fpt.com.vn, aisg.devteam@gmail.com. Unfortunatelly with no succes. Please register a 1:1 gestion on https://seller.samsungapps.com/tv/assistance/csportal/create# (category Tizen->Others). Title it as 'JuvoPlayer Tizen dot net developer signature files'. In the 'Device Where Found' box enter the TV set details (model, DUID etc.)
With the above it should be possible to help You over the Seller Office portal.

**Comment by AliDem** [comment] 2020-11-14 15:52
I also have the partnership and I have the same problem.
newer versions of xamarin.forms are no longer supported, we need to edit the source code of "Xamarin.Forms.Platform.Tizen" and downgrade the version of SkiaSharp to 1.60.3 again.

All seem to be ok, but I still get an error when using the mentioned version of the SkiaSharp.Views.Tizen library.
"SkiaSharp.Views.Tizen.dll directly refers to a forbidden assembly: libgGLESv2.so"

And I have no certificate error, I have another application with which I use SkiaSharp for some tasks without using this library and everything works fine if we stick with the old versions of Xamarin. Too bad.

Thank you:)

**Comment by ranvirsingh** [comment] 2021-08-15 05:46
> I also have the partnership and I have the same problem.
> newer versions of xamarin.forms are no longer supported, we need to edit the source code of "Xamarin.Forms.Platform.Tizen" and downgrade the version of SkiaSharp to 1.60.3 again.
> 
> All seem to be ok, but I still get an error when using the mentioned version of the SkiaSharp.Views.Tizen library.
> "SkiaSharp.Views.Tizen.dll directly refers to a forbidden assembly: libgGLESv2.so"
> 
> And I have no certificate error, I have another application with which I use SkiaSharp for some tasks without using this library and everything works fine if we stick with the old versions of Xamarin. Too bad.
> 
> Thank you:)

Was this resolved by any means?

**Comment by ppaneksamsung** [comment] 2021-08-16 09:30
@ranvirsingh,

Could you share some details about your environment, like TV model, packages versions (Xamarin.Forms, SkiaSharp, SkiaSharp.Views, SkiaSharp.Views.Forms)? If possible, could you prepare a sample application for reproduction? As far as I understand:
- you're the Samsung partner
- your application is signed by a 'partner' certificate
- you received additional security certificates to disable security mechanism, which prevents to launch a Tizen .NET application if it loads any platform libraries directly (like libSkiaSharp.so or libGLESv2.so).
- your app can load libSkiaSharp.so without any issues
- however, for some reason, your app is not launched due to "SkiaSharp.Views.Tizen.dll directly refers to a forbidden assembly: libGLESv2.so"

Is it correct?

**Comment by ppaneksamsung** [comment] 2021-08-17 13:26
@ranvirsingh,

> Do I need all these to develop and make apps available on Samsung TV store?

Basically, yes. Here you can find more information about the process:
https://developer.samsung.com/smarttv/develop/distribute/seller-office/membership/becoming-partner.html

@pbsamsung may assist you in case of any problems.

And regarding this security mechanism, which prevents to launch an application if it loads any plaform libraries directly - Tizen TVs 2021 (and later) don't have it. If you own the latest Tizen TV model, then you don't need any agreement with Samsung to develop and test your app on your local TV, _if it refers to any forbidden dlls_. **You still need to be a partner if you want to submit an app to Samsung TV store**, but at least you can verify Tizen TV .NET environment on your own. Additionally, you can choose any SkiaSharp version on Tizen TVs 2021. Previous models forced developers to stick with SkiaSharp 1.60.3.

**Comment by Preclikos** [comment] 2021-09-03 08:28
Hello, i read all post here and finish i basicali if i have 2 TV model 2019 and 2020 still need to be partner to can develop/debug app based on JuvoPlayer for this models?
If i buy newer TV model 2021 ( can develop/debug without problems/restrictions ) need to be partner only for app Release?

**Comment by ppaneksamsung** [comment] 2021-09-03 08:35
That's basically correct, however currently we investigate one issue related to DRMs on some 2021 models, more on this is here: https://github.com/flutter-tizen/flutter-tizen/issues/217

**Comment by Preclikos** [comment] 2021-09-03 08:43
Thx for fast reply

i dont use DRM :) in my case maybe only need clean it from solution :/
I will try the way with partner ship and features unlock actually wait for partner response in my region => sorry i have frustration from this process no or slow responses on 1:1 and other threads or Q&A etc...

**Closed** 2023-09-13 13:22 UTC

**Comment by talebi** [comment] 2024-07-02 03:48
@pbsamsung or anyone else - how to get it running on an actual TV? I have an approved partner program and already sent a 1:1 to get the required certificates but haven't heard anything in a week? is this still supported?
